## Numpy

In [2]:
import numpy as np

In [4]:
vector = np.array([0,1,2,3,4,5])
print(vector)

[0 1 2 3 4 5]


In [9]:
vectorDos = np.array([1,2,3,4,5], dtype = np.float32)
print(vectorDos)

vector.dtype = np.float16
print(vector)

vectorTres = np.array([1,2,3,4,5])
vectorTres = vectorTres.astype(np.float32)
print(vectorTres)

[1. 2. 3. 4. 5.]
[0.0e+00 0.0e+00 6.0e-08 0.0e+00 1.2e-07 0.0e+00 1.8e-07 0.0e+00 2.4e-07
 0.0e+00 3.0e-07 0.0e+00]
[1. 2. 3. 4. 5.]


In [11]:
print(vectorTres[3])

4.0


In [14]:
vectorCuatro = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(vectorCuatro[0:8:2])

[0 2 4 6]


In [25]:
a = np.array([0,1,2])
b = np.array([0,-1,-3])
c = np.array([1,1,1])

print(a+b)
print(a-b)
print(a*b)
print(a/c)
print(2*a)
demo = a>= 1
print(demo)
print(a**a)

[ 0  0 -1]
[0 2 5]
[ 0 -1 -6]
[0. 1. 2.]
[0 2 4]
[False  True  True]
[1 1 4]


Rutinas linspace,arange para generar numeros entre un rango entre dos numeros dados. a<=x<=b -->linspace a<=x<b -->arange

In [32]:
print(np.linspace(3,15,4))
print(np.arange(0,16,1))

[ 3.  7. 11. 15.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [50]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.arange(0,16,1)
print(matrix)
print(matrix.shape)
print(a.shape)
nueva = matrix.reshape(9,)
print(nueva)
print(matrix)
b = a.reshape(2,8)
print(b)

mt1=[[34,3],[67,7]]
mt2=[[11,2],[78,3]]
mt3=[[23,32],[90,1]]
arr1=np.array([mt1,mt2,mt3])
print(arr1.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(16,)
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(3, 2, 2)


In [68]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m.shape)
c1 = m[:2,1:3]
c2 = m[2:,:]
print(c2.shape)
print(c2[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(1, 3)
8


In [70]:
A = np.array([[2,-1],[1,3]])
b = np.array([3,5])
c = np.linalg.solve(A,b)
print(c)
print(A@c) #multiplicacion de matrices @

[2. 1.]
[3. 5.]
