Ejercicio 1

In [1]:
import numpy as np

In [2]:
A = np.array([[1,4],[-1,3],[2,-9]])
ceros = np.zeros((3,2))
print(A)

[[ 1  4]
 [-1  3]
 [ 2 -9]]


In [3]:
r = A + ceros
print(r)

[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]


In [4]:
r = A - ceros
print(r)

[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]


In [5]:
r = A - A
print(r)

[[0 0]
 [0 0]
 [0 0]]


Ejercicio 2

In [6]:
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])
# A + 3B
r = A + (B * 3)
print(r)
#no se puede realizar la suma de matrices de diferentes dimensiones

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [7]:
# A x B
r = A @ B
print(r)

[[12 -6  3]
 [-4 12 14]]


In [40]:
# A con potencia 3
r = A @ A @ A
print(r)

[[ 27   0]
 [-49 125]]


In [42]:
# B con potencia 2
r = B @ B
print(r)
# no se puede calcular la potencia de la matriz B porque no es una matriz cuadrada 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [43]:
# (5A)B
r = (A * 5) @ B
print(r)

[[ 60 -30  15]
 [-20  60  70]]


Ejercicio 3

In [13]:
restaurantes = np.array([[30,15,4],[25,18,8]])
tiendas = np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print(tiendas.T)
costoPorTienda = restaurantes@tiendas.T
print(costoPorTienda)
print("Tienda 1", (costoPorTienda[0,0]+costoPorTienda[1,0]))
print("Tienda 2", (costoPorTienda[0,1]+costoPorTienda[1,1]))

[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
[[ 87.   88.9]
 [105.6 107.1]]
Tienda 1 192.6
Tienda 2 196.0


Ejercicio 4

In [50]:
almacenes = np.array([[200,75],[150,100],[100,125]])
transportes = np.array([[1.5,1.75],[1.,1.5],[2.,1.]])
#obtenemos la transpuesta de la matriz transportes
print(transportes.T)
#realizamos la multiplicacion de matrices
costoPorAlmacen = transportes.T @ almacenes
print(costoPorAlmacen)
#obtenemos el costo total por transporte sumando las cantidades obtenidas por almacen
print("Camión", (costoPorAlmacen[0,0] + costoPorAlmacen[0,1]))
print("Tren", (costoPorAlmacen[1,0] + costoPorAlmacen[1,1]))

[[1.5  1.   2.  ]
 [1.75 1.5  1.  ]]
[[650.   462.5 ]
 [675.   406.25]]
Camión 1112.5
Tren 1081.25


Ejercicio 5

In [55]:
#3x + 2y = 6
#6x + 4y = -9
A = np.array([[3,2],[6,4]])
B = np.array([6,-9])
C = np.linalg.solve(A,B)
#Este sistema de ecuaciones no tiene solucion

LinAlgError: Singular matrix

In [57]:
#x + y = 3
#x - 4y = 1
A = np.array([[1,1],[1,-4]])
B = np.array([3,1])
C = np.linalg.solve(A,B)
print(C)
#Comprobando el resultado
print(A @ C)

[2.6 0.4]
[3. 1.]


In [8]:
#2x − y + 2z = 3
#2x + 3y − z = 0
#x + 2y + 2z = −12
A = np.array([[2,-1,2],[2,3,-1],[1,2,2]])
B = np.array([3,0,-12])
C = np.linalg.solve(A,B)
print(C)
#Comprobando el resultado
R = A @ C
print(R[:].astype(np.float64))

[ 3.65217391 -3.7826087  -4.04347826]
[ 3.0000000e+00  8.8817842e-16 -1.2000000e+01]
